//! Module and file output.

use std::collections::HashMap;
use std::path::Path;

use proc_macro2::TokenStream;
use quote::quote;

use crate::Error;

/// Write generated modules to the output directory.
pub fn write_modules(
    out_dir: &Path,
    modules: &HashMap<String, TokenStream>,
    skip_format: bool,
) -> Result<(), Error> {
    for (module_name, tokens) in modules {
        let file_name = format!("{}.rs", module_name);
        let file_path = out_dir.join(&file_name);

        // Add standard imports
        let full_code = quote! {
            // @generated by protomon-build. Do not edit.
            #![allow(clippy::all)]
            #![allow(warnings)]
            #![allow(missing_docs)]

            #tokens
        };

        let code_string = if skip_format {
            full_code.to_string()
        } else {
            format_code(&full_code)?
        };

        std::fs::write(&file_path, code_string)?;

        // Tell Cargo to rerun if output changes
        println!("cargo:rerun-if-changed={}", file_path.display());
    }

    // Generate a mod.rs or lib include file
    let include_path = out_dir.join("mod.rs");
    let mod_decls: Vec<TokenStream> = modules
        .keys()
        .map(|name| {
            let mod_name: syn::Ident = syn::parse_str(name)
                .map_err(|e| Error::SynParse(format!("Invalid module name '{}': {}", name, e)))?;
            Ok(quote!(pub mod #mod_name;))
        })
        .collect::<Result<Vec<_>, Error>>()?;

    let mod_content = quote! {
        // @generated by protomon-build. Do not edit.
        #(#mod_decls)*
    };

    let mod_string = if skip_format {
        mod_content.to_string()
    } else {
        format_code(&mod_content)?
    };

    std::fs::write(&include_path, mod_string)?;

    Ok(())
}

/// Format code using prettyplease.
fn format_code(tokens: &TokenStream) -> Result<String, Error> {
    let file: syn::File =
        syn::parse2(tokens.clone()).map_err(|e| Error::SynParse(e.to_string()))?;
    Ok(prettyplease::unparse(&file))
}
