//! Conformance tests for protomon.
//!
//! This crate reads binary protobuf files generated by the C++ protobuf library
//! and verifies that protomon decodes them correctly.

// Include the generated protobuf code
pub mod protos {
    include!(concat!(env!("OUT_DIR"), "/mod.rs"));
}

#[cfg(test)]
mod tests;
